@extends('layouts.app')
@section('content')
<div class="mb-4">
    <h1 class="text-xl font-semibold">Payments</h1>
    <p class="mt-1 text-sm text-slate-600">Payments are generated from contracts and can be recorded when rent is collected.</p>
</div>
<form class="mb-4 grid gap-3 rounded border bg-white p-3 sm:grid-cols-[1fr_auto_auto]"><select name="status" class="tap-target rounded border p-2"><option value="">All statuses</option>@foreach(['pending','paid','partial','overdue'] as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="tap-target rounded bg-slate-900 px-4 text-white">Filter</button><a class="tap-target flex items-center justify-center rounded border bg-white px-4" href="{{ route('payments.index', ['overdue' => 1]) }}">Overdue</a></form>
<x-table min-width="min-w-[68rem]"><thead><tr><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Due date</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Tenant</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Unit</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Contract</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Amount</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Status</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Paid date</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Action</th></tr></thead><tbody>@foreach($payments as $payment)<tr class="border-t"><td class="p-4 whitespace-nowrap">{{ $payment->due_date->toDateString() }}</td><td class="p-4 font-medium">{{ $payment->contract?->tenant?->full_name ?? 'N/A' }}</td><td class="p-4 whitespace-nowrap">{{ $payment->contract?->unit?->unit_number ?? 'N/A' }}</td><td class="p-4 whitespace-nowrap">{{ $payment->contract?->contract_number ?? 'N/A' }}</td><td class="p-4 whitespace-nowrap">{{ number_format($payment->amount_due, 2) }}</td><td class="p-4 whitespace-nowrap"><span class="rounded bg-slate-100 px-2 py-1 text-xs">{{ $payment->status }}</span></td><td class="p-4 whitespace-nowrap">{{ $payment->payment_date?->toDateString() ?? 'N/A' }}</td><td class="p-4 whitespace-nowrap">@if($payment->status === 'paid')<a class="tap-target inline-flex items-center rounded border px-3 text-slate-700" href="{{ route('payments.show', $payment) }}">View receipt</a>@else<a class="tap-target inline-flex items-center rounded border px-3 text-slate-700" href="{{ route('payments.edit', $payment) }}">Record payment</a>@endif</td></tr>@endforeach</tbody></x-table>
{{ $payments->links() }}
@endsection
