@extends('layouts.app')
@section('content')
<div class="mb-4">
    <h1 class="text-xl font-semibold">{{ __('payments.title') }}</h1>
    <p class="mt-1 text-sm text-slate-600">{{ __('payments.description') }}</p>
</div>
<form class="mb-4 grid gap-3 rounded border bg-white p-3 sm:grid-cols-[1fr_auto_auto]"><select name="status" class="tap-target rounded border p-2"><option value="">{{ __('payments.all_statuses') }}</option>@foreach(['pending','paid','partial','overdue','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ __('payments.statuses.'.$status) }}</option>@endforeach</select><button class="tap-target rounded bg-slate-900 px-4 text-white">{{ __('payments.filter') }}</button><a class="tap-target flex items-center justify-center rounded border bg-white px-4" href="{{ route('payments.index', ['overdue' => 1]) }}">{{ __('payments.overdue') }}</a></form>
<x-table min-width="min-w-[68rem]"><thead><tr><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.due_date') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.tenant') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.unit') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.contract') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.amount') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.status') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.paid_date') }}</th><th class="p-4 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">{{ __('payments.columns.action') }}</th></tr></thead><tbody>@foreach($payments as $payment)<tr class="border-t"><td class="p-4 whitespace-nowrap"><span dir="ltr">{{ $payment->due_date->toDateString() }}</span></td><td class="p-4 font-medium">{{ $payment->contract?->tenant?->full_name ?? __('payments.not_available') }}</td><td class="p-4 whitespace-nowrap"><span dir="ltr">{{ $payment->contract?->unit?->unit_number ?? __('payments.not_available') }}</span></td><td class="p-4 whitespace-nowrap"><span dir="ltr">{{ $payment->contract?->contract_number ?? __('payments.not_available') }}</span></td><td class="p-4 whitespace-nowrap"><span dir="ltr">{{ number_format($payment->amount_paid, 2) }} / {{ number_format($payment->amount_due, 2) }}</span></td><td class="p-4 whitespace-nowrap"><span class="rounded bg-slate-100 px-2 py-1 text-xs">{{ __('payments.statuses.'.$payment->status) }}</span>@if($payment->status === 'cancelled')<span class="mt-1 block text-xs text-slate-500">{{ __('payments.lifecycle.cancelled_due_to_contract_termination') }}</span>@endif</td><td class="p-4 whitespace-nowrap"><span dir="ltr">{{ $payment->payment_date?->toDateString() ?? __('payments.not_available') }}</span></td><td class="p-4 whitespace-nowrap">@if($payment->amount_paid > 0)<a class="tap-target inline-flex items-center rounded border px-3 text-slate-700" href="{{ route('payments.show', $payment) }}">{{ __('payments.view_receipt') }}</a>@elseif($payment->status === 'cancelled')<span class="text-sm text-slate-500">{{ __('payments.lifecycle.cancelled_due_to_contract_termination') }}</span>@else<a class="tap-target inline-flex items-center rounded border px-3 text-slate-700" href="{{ route('payments.edit', $payment) }}">{{ __('payments.record_payment') }}</a>@endif</td></tr>@endforeach</tbody></x-table>
{{ $payments->links() }}
@endsection
